name: Cloud Tests

on:
  workflow_dispatch: # Добавляет кнопку "Run workflow"
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  gcc-tests:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 2
    
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, ubuntu-24.04-arm]
        standard: [C++98, C++11]

    steps:
      - name: Download and Checkout Code
        uses: actions/checkout@v4

      - name: Compiling Tests (Linux)
        if: contains(matrix.os, 'ubuntu')
        run: |
          cd tests/
          chmod +x ./make_test.sh
          bash ./make_test.sh ${{ matrix.standard }}

      - name: Executing Tests (Linux)
        if: contains(matrix.os, 'ubuntu')
        run: |
          cd tests/
          ./tests

      - name: Compiling Tests (Windows)
        if: contains(matrix.os, 'windows')
        shell: cmd
        run: |
          cd tests/
          make_test.bat ${{ matrix.standard }} x64

      - name: Executing Tests (Windows)
        if: contains(matrix.os, 'windows')
        shell: cmd
        run: |
          cd tests/
          tests.exe

  qemu-riscv-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [64] #32
        standard: [C++98] #C++11

    steps:
      - name: Download and Checkout Code
        uses: actions/checkout@v4

      - name: Compiling & Executing Tests on RISC-V (x${{ matrix.arch }}, QEMU)
        uses: uraimo/run-on-arch-action@v3
        timeout-minutes: 3
        with:
          arch: riscv${{ matrix.arch }}
          distro: ubuntu22.04
          run: |
            apt update -q && apt install g++ -y -q --no-install-recommends
            cd tests/
            chmod +x ./make_test.sh
            bash ./make_test.sh ${{ matrix.standard }}
            ./tests

  # win7-gcc-4.9.2:
    # runs-on: self-hosted win7
  # win7-gcc-3.4.2:
    # runs-on: self-hosted win7
  # debian-old-gcc-4.9.2:
    # runs-on: self-hosted linux2.6